
#路径
paths:
    train_dir: "./imgs/train"
    val_dir: "./imgs/val"
    test_dir: "./imgs/test"
    checkpoint_dir: "./checkpoint"

# 基础训练配置
train:
    epochs: 100               # 训练总轮数
    learning_rate: 0.01      # 学习率
    optimizer: "adam"         # 优化器类型: adam, sgd
    device: 'mps'             # mps cpu cuda
                

dataset:
    dataloader:
        batch_size: 64           # 每批训练样本数
        num_workers: 8            # 多进程
# 下面两个权重设置 可以都为False 对于较轻的类别不均衡 采样设置True,loss设置False
# 对于严重的类别不均衡 采样设置为False,loss设置为True  loss为true时 会覆盖sampling
    sampling_weight: False             # 是否权重采样 (训练时)
    loss_weight: False         # 计算loss时 是否应用权重 

# 模型相关参数
model:
    name: "DenseNet"            # 可选: ResNet, DenseNet
    num_classes: 10           # 动物类别数量
  # pretrained: true          # 是否使用预训练模型

# 数据预处理参数 (对应 utils/pretreatment.py)
preprocessing:
    shape: [224, 224]        # 图像缩放尺寸
    use_letter: True
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  
  
